apiVersion: v1
kind: Service
metadata:
  name: mrz-reader
  namespace: hostshield
spec:
  ports:
    - port: 8000
  selector:
    app: mrz-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrz-reader
  namespace: hostshield
spec:
  replicas: 1 # Stateless, can scale if needed
  selector:
    matchLabels:
      app: mrz-reader
  template:
    metadata:
      labels:
        app: mrz-reader
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: mrz-reader
          image: ghcr.io/unclebob20/host-shield/mrz-reader:latest # REPLACE with your registry
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
