apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: hostshield
spec:
  ports:
    - port: 80
  selector:
    app: web-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: hostshield
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: web-client
          image: ghcr.io/unclebob20/host-shield/web-client:latest # REPLACE with your registry
          ports:
            - containerPort: 80
          imagePullPolicy: Always
