apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostshield-ingress
  namespace: hostshield
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - app.hostshield.sk
      secretName: hostshield-tls
  rules:
    - host: app.hostshield.sk
      http:
        paths:
          # API Requests exposed via /api prefix
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-server
                port:
                  number: 3000
          # Frontend for everything else
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-client
                port:
                  number: 80
